services:

  postgres:
    image: pgvector/pgvector:pg16

    container_name: weather-rag-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: weather_rag
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password

    ports:
      - "5432:5432"

    volumes:
      - weather_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U weather_user -d weather_rag"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:

  weather_postgres_data:
